local list = {
    { key = { "o", "<2-LeftMouse>" }, action = "edit" },
    { key = { "O" }, action = "edit_no_picker" },
    { key = { "<2-RightMouse>", "<C-]>", "<cr>" }, action = "cd" },
    { key = "v", action = "vsplit" },
    { key = "i", action = "split" },
    { key = "t", action = "tabnew" },
    { key = "<", action = "prev_sibling" },
    { key = ">", action = "next_sibling" },
    { key = "P", action = "parent_node" },
    { key = "<BS>", action = "close_node" },
    { key = "<Tab>", action = "preview" },
    { key = "K", action = "first_sibling" },
    { key = "J", action = "last_sibling" },
    { key = "I", action = "toggle_ignored" },
    { key = "H", action = "toggle_dotfiles" },
    { key = "r", action = "refresh" },
    { key = "a", action = "create" },
    { key = "n", action = "create" },
    { key = "d", action = "remove" },
    { key = "D", action = "trash" },
    { key = "R", action = "rename" },
    { key = "<f2>", action = "full_rename" },
    { key = "x", action = "cut" },
    { key = "c", action = "copy" },
    { key = "p", action = "paste" },
    { key = "y", action = "copy_name" },
    { key = "Y", action = "copy_path" },
    { key = "gy", action = "copy_absolute_path" },
    { key = "[c", action = "prev_git_item" },
    { key = "]c", action = "next_git_item" },
    { key = "-", action = "dir_up" },
    { key = "s", action = "system_open" },
    { key = "q", action = "close" },
    { key = "g?", action = "toggle_help" },
}

require("nvim-tree").setup({
    renderer = {
        icons = {
            glyphs = {
                default = "",
                symlink = "",
                git = {
                    unstaged = "",
                    staged = "﫠",
                    unmerged = "",
                    renamed = "➜",
                    untracked = "",
                    deleted = "﫧",
                    ignored = "_",
                },
                folder = {
                    arrow_open = "",
                    arrow_closed = "",
                    default = "",
                    open = "",
                    empty = "",
                    empty_open = "",
                    symlink = "",
                    symlink_open = "",
                },
            },
        },
    },
    diagnostics = {
        enable = true,
        icons = {
            hint = "",
            info = "",
            warning = "",
            error = "",
        },
    },
    git = {
        enable = true,
        ignore = false,
        timeout = 500,
    },
    view = {
        -- mappings = {
        --     custom_only = false,
        --     list = list,
        -- },
    },
    sync_root_with_cwd = true,
    hijack_cursor = true,
})
